### ISSUE TITLE
Link to exploring the funding award is broken

### ISSUE THREAD

**Issue by hlapp** [fairdataihub/fairdataihub.org#147]
**Describe the bug**
The [link to "Explore the award on NIH Reporter"](https://github.com/fairdataihub/fairdataihub.org/blob/main/src/components/fairshare/info.tsx#L185) results in what looks like a 404.

**To Reproduce**

1. Go to https://fairdataihub.org/fairshare
2. Click on "Explore the award on NIH Reporter"

**Expected behavior**
A page at NIH describing the award on NIH Reporter.

**Comment by megasanjay** [comment]
@bvhpatel

**Comment by megasanjay** [comment]
Fixed in 5d40568467f338659b3382acbd928d7e189a629e
